### ISSUE TITLE
Android: FATAL EXCEPTION

### ISSUE THREAD

**Issue by RGump** [airbnb/react-native-maps#1051]
FATAL EXCEPTION: main
                                                            Process: com.yourhour, PID: 2981
                                                            java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zze)"
                                                                at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                                at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                                                                at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                                                                at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)
                                                                at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:73)
                                                                at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
                                                                at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                                at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
                                                                at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

any thoughts?

**Comment by juanmanuelarze** [comment]
same

**Comment by minhcasi** [comment]
the same :((

**Comment by cnf271** [comment]
Same issue with google maps !

**Comment by enniel** [comment]
For fix this problem upgrade version play servises to latest version
```
dependencies {
...
    compile(project(':react-native-maps')){
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.2.1'
    compile 'com.google.android.gms:play-services-maps:10.2.1'
...
}
```

**Comment by felipecsl** [comment]
release v.0.15.0 is upgraded to version `10.2.4`

**Comment by nitish24p** [comment]
I'm still getting this. The above solution didnt work

**Comment by tonygentilcore** [comment]
@nitish24p I had to update to the current latest (`11.0.4`) for it to work. Did you try that or one of the now dated version numbers in this thread?
