### ISSUE TITLE
RN 0.41.2 android error -  cannot find setProgressTintList

### ISSUE THREAD

**Issue by rborn** [airbnb/react-native-maps#1057]
I'm using it with the last https://github.com/wix/react-native-navigation and I get this error:

Any ideas? Thank you 😸 

~~~
02-23 15:55:09.472: I/dalvikvm(6142): Could not find method android.widget.ProgressBar.setProgressTintList, referenced from method com.airbnb.android.react.maps.AirMapView.setLoadingIndicatorColor
02-23 15:55:09.612: E/unknown:React(6142): 	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)
02-23 15:55:09.612: E/unknown:React(6142): 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:73)
02-23 15:55:09.612: E/unknown:React(6142): 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
~~~

**Comment by rborn** [comment]
Ignore me, I was using 0.12.4 and I forgot to set to the parent view `flex:1` 😞
