### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by ayyoobcastro** [airbnb/react-native-maps#1061]
hi guys 

i just installed map using 
npm install react-native-maps --save

then linked using react-native link

after these all My app is not building. why that

can you guys please help me..............
waiting for the reply

**Comment by AugustoAleGonZhipCode** [comment]
Same here. I did on Android. And it is not working at all.

FATAL EXCEPTION: AsyncTask #3
                                                              Process: com.zhipcode, PID: 22463
                                                              java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                  at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
                                                                  at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
                                                                  at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                                  at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
                                                                  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:206)
                                                                  at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:71)
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:145)
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:142)
                                                                  at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
                                                                  at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:958)
                                                                  at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:863)
                                                                  at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
                                                                  at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
                                                                  at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                  at java.lang.Thread.run(Thread.java:818) 

This the console.

**Comment by eman1000** [comment]
I had the same problem. My solution was to use react-native v0.39.0. Just init your project like this react-native init --version="0.39.0" NAME_OF_YOUR_PROJECT

**Comment by AugustoAleGonZhipCode** [comment]
I solved it checking the node_modules/react-native-myplugin because there was a version that I was using that had some conflicts.
