### ISSUE TITLE
FATAL EXCEPTION help plz

### ISSUE THREAD

**Issue by juanmanuelarze** [airbnb/react-native-maps#1077]
FATAL EXCEPTION: main
                                                            Process: com.reactapp, PID: 2678
                                                            java.lang.NoSuchMethodError: No static method zzA(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/com.reactapp-2/base.apk)
                                                                at com.google.android.gms.maps.internal.zzai.zzbq(Unknown Source)
                                                                at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                                at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:67)
                                                                at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
                                                                at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                                at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
                                                                at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
                                                                at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                at android.os.Handler.handleCallback(Handler.java:746)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by jnrepo** [comment]
@juanmanuelarze were you able to find a solution?

**Comment by juanmanuelarze** [comment]
Yes, i change the versión of play-service-maps to 10.2.0

compile 'com.google.android.gms:play-service-maps:10.2.0'

**Comment by jnrepo** [comment]
@juanmanuelarze THANKS, that was it!
