### ISSUE TITLE
Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setPadding(int, int, int, int)' on a null object reference

### ISSUE THREAD

**Issue by the-simian** [airbnb/react-native-maps#1227]
- this is on version 0.13.1
- this only seems to happen in release mode
- this does not affect the majority of users, have not been able to reproduce this ourselves, but endusers have experienced it.

```
java.lang.NullPointerException Attempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setPadding(int, int, int, int)' on a null object reference 
    AirMapView.java:575 com.airbnb.android.react.maps.AirMapView.fitToCoordinates
    AirMapManager.java:228 com.airbnb.android.react.maps.AirMapManager.receiveCommand
    AirMapManager.java:29 com.airbnb.android.react.maps.AirMapManager.receiveCommand
    NativeViewHierarchyManager.java:703 com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand
    UIViewOperationQueue.java:257 com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute
    UIViewOperationQueue.java:782 com.facebook.react.uimanager.UIViewOperationQueue$2.run
    UIViewOperationQueue.java:829 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:44 com.facebook.react.uimanager.UIViewOperationQueue.access$1500
    UIViewOperationQueue.java:868 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedChoreographerFrameCallback.java:32 com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame
    ReactChoreographer.java:131 com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    Choreographer.java:918 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:695 android.view.Choreographer.doCallbacks
    Choreographer.java:628 android.view.Choreographer.doFrame
    Choreographer.java:906 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:158 android.os.Looper.loop
    ActivityThread.java:7237 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main
```

**Comment by the-simian** [comment]
I found one reference to this error here: https://github.com/airbnb/react-native-maps/pull/628

**Comment by MyTotoro** [comment]
I'm having the same exact issue

![image](https://cloud.githubusercontent.com/assets/3621921/25361128/8113eac2-291a-11e7-87c1-d793e6c5a5e6.png)

**Comment by the-simian** [comment]
hey @MyTotoro , can you post the code with the `setTimeout`? not 100% what you mean by your comment.

I'd still like to know the root cause of this. Its been very persistant

**Comment by henrikra** [comment]
This is the most common crash with our app at the moment. About 13 crashes every 24hours :/

**Comment by MyTotoro** [comment]
@the-simian 
```
componentDidMount () {

    setTimeout( () => {
      this.map.fitToCoordinates(
        this.state.LOCATIONS,
        {
          edgePadding: { top: 50, right: 100, bottom: 450, left: 100 },
          animated: true
        }
      )
    }, 2500);
  }

...
render () {
    return (
        <MapView
          ref={(ref) => { this.map = ref }}
```

This is what I have, state is set accordingly. It's pretty hacky

**Comment by the-simian** [comment]
@MyTotoro , ok so you wrapped fitToCoorrdinates itself in setTimeout. I'm going to try this and see if it prevents the crashes. It doesn't matter in our app if fitToCoordinates gets shifted back in the event queue, so I don't think this will be an issue. The map is mostly a side effect of state.

Thanks for the reply btw, this is really helpful.

**Comment by iiitmahesh** [comment]
@the-simian Any Update?? Any workaround..!

**Comment by lupakgabor** [comment]
You sholud put it onLayout event, not componentDidUpdate.
"If called in ComponentDidMount in android, it will cause an exception. It is recommended to call it from the MapView onLayout event"

**Comment by MyTotoro** [comment]
@lupakgabor where's the documentation for that? I looked around before implementing the hackaround

**Comment by the-simian** [comment]
sorry @iiitmahesh , I'll need to observe more before I can tell you if this definitively fixed the issue, but I haven't forgotten to reply when I can confirm

**Comment by the-simian** [comment]
I tried the fix that was suggested, and while I did not get the error above, now I am gettign another one:
```
java.lang.NullPointerException: 
  at com.airbnb.android.react.maps.AirMapView.fitToCoordinates(AirMapView.java:576)
  at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:217)
  at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:29)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:703)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:258)
  at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
  at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
  at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
  at android.view.Choreographer.doFrame(Choreographer.java:603)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
  at android.os.Handler.handleCallback(Handler.java:743)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:171)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by vraghavachari** [comment]
@MyTotoro I'm using react-native-maps v0.16.2 and calling fitToCoordinates from MapView onLayout but I still get the same error

**Comment by MyTotoro** [comment]
@vraghavachari  So it might be because you don't have a size when you're calling it:

make the container view for the map 500 by 500, then in `componentDidMount` you can manipulate it:

```
timer.setTimeout(this, 'zoom', () => {
            try {
              this.map.fitToCoordinates(
                [...],
                {
                  edgePadding: { top: 40, right: 40, bottom: 40, left: 40 },
                  animated: true
                }
              )
            } catch (e) { }
          }, 100)
```

I'm using react-native-timer to manage the timer contexts

**Comment by Kosai106** [comment]
This is still very much an issue, even when using `onLayout` - However adding a timeout seems to have fixed the crashing that happened in our application. Still, it feels like a hack and it would be best if it wasn't necessary.

**Comment by vraghavachari** [comment]
Moving the fitToCoordinates() to onMapReady seems to fix the crash. I'd tested this unsuccessfully in the past (I don't recall if I was using a diff map version then) but it seems to be working now - I did do good amount of testing. 

```
onLayout={() => { setTimeout(() => {
            this.alertMapRef.fitToCoordinates([this.props.alertInfo.position], true);
            this.alertMapRef.animateToRegion(this.props.alertInfo.position, 750);
        }, 1); }}
```

**Comment by Kosai106** [comment]
@vraghavachari I'll try this tomorrow and report back - It seems like a better solution than using a timeout for sure.

**Comment by davidroman0O** [comment]
Thx everyone, i was struggling with this issue!
