### ISSUE TITLE
Android sdk app crashes after integrating Firebase with Google maps

### ISSUE THREAD

**Issue by kshitijakarkar** [airbnb/react-native-maps#1264]
--------- beginning of crash
04-21 17:23:24.682 2887-2887/com.example.kshitija.googlemaps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.kshitija.googlemaps, PID: 2887
                                                                               java.lang.NoSuchMethodError: No virtual method zzTt()Z in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/com.example.kshitija.googlemaps-1/split_lib_dependencies_apk.apk:classes13.dex)
                                                                                   at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
                                                                                   at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
                                                                                   at com.example.kshitija.googlemaps.MapsActivity.<init>(MapsActivity.java:22)
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                   at java.lang.Class.newInstance(Class.java:1572)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
04-21 17:23:32.362 2887-2887/? I/Process: Sending signal. PID: 2887 SIG: 9

**Comment by KarlosQ** [comment]
Probably the problem is a distinct google-services version.

Check in your project/node_modules/react-native-maps/android/build.gradle the version of play-services. You must use the same version in all components.

**Comment by kshitijakarkar** [comment]
Hello @KarlosQ  I found the solution. The problem was I had to import existing Google project (in my case google maps) into firebase through firebase console. I was running 2 different projects which is why the app was crashing even though I had packages and SHA1 key stored for both.

**Comment by henrikra** [comment]
@kshitijakarkar Then close this issue?

**Comment by kshitijakarkar** [comment]
@henrikra Yes. That was the solution in my case.
