### ISSUE TITLE
Map not showing because com.google.android.gms.dynamic.zza$1

### ISSUE THREAD

**Issue by aldente05** [airbnb/react-native-maps#1383]
`FATAL EXCEPTION: main
                                                             Process: com.etalent, PID: 16239
                                                             java.lang.IncompatibleClassChangeError: com.google.android.gms.dynamic.zza$1
                                                                 at com.google.android.gms.dynamic.zza.<init>(Unknown Source)
                                                                 at com.google.android.gms.maps.MapView$zzb.<init>(Unknown Source)
                                                                 at com.google.android.gms.maps.MapView.<init>(Unknown Source)
                                                                 at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:0)
                                                                 at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
                                                                 at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
                                                                 at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                                 at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:781)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:843)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:889)
                                                                 at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                 at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                                                 at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

On my JS

import React from 'react';
import {Text, View, Dimensions, StyleSheet} from 'react-native';
import Map from 'react-native-maps'
import Style from '../../utils/Style'

export default class OnGoing extends React.Component {
    render() {
        const { region } = this.props;
        console.log(region);

        return (
            <View>
                <View style={styles.container}>
                    <Map
                        style={styles.map}
                        region={{
                            latitude: 37.78825,
                            longitude: -122.4324,
                            latitudeDelta: 0.015,
                            longitudeDelta: 0.0121,
                        }}
                    >
                    </Map>
                </View>

                <View style={{marginLeft : 20}}>
                    <Text>Toys & Comic Fair 2017</Text>
                    <Text note>Taman Impian Jaya Ancol, Jakarta</Text>

                    <View style={Style.containerInLine}>
                        <Text style={{flex : 1, position: 'relative', left :0}}>1 hour</Text>
                        <Text style={{flex : 1, position: 'relative', right :0}}>1 ml</Text>
                    </View>
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        // ...StyleSheet.absoluteFillObject,
        height: Dimensions.get('window').height - 200,
        width: Dimensions.get('window').width,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    map: {
        // ...StyleSheet.absoluteFillObject,
        top : 0,
        bottom : 0,
        left : 0,
        right : 0,
        position : 'absolute'
    },
});

map not showing and what should i do?

**Comment by aldente05** [comment]
i solve this issue 

check setting.gradle
just add this once

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

these error because duplicate on setting.gradle

**Comment by 3210jr** [comment]
Hey @aldente05 , I have the same issue but my settings.graddle file looks just fine.

Any ideas?

**Comment by aldente05** [comment]
re link library.
and edit on setting.gradle and gradle app.
duplicate init or not.
remove the duplicate one.

on app gradle
`compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

compile 'com.google.android.gms:play-services-base:11.+'
compile 'com.google.android.gms:play-services-maps:11.+'
`

and add this after dependencies

`dependencies {.....
}

apply plugin: 'com.google.gms.google-services'
`

i use
compileSdkVersion 23
buildToolsVersion "25.0.3"
