### ISSUE TITLE
Android app crashing on loading MapView

### ISSUE THREAD

**Issue by nitish24p** [airbnb/react-native-maps#1707]
I get the following crash logs
```
ACRA caught a AbstractMethodError for com.kyepot.india.chitfund
10-17 13:16:09.551  8226  8226 E ACRA    : java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo)"
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:130)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
10-17 13:16:09.551  8226  8226 E ACRA    : 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
```

My build.gradle file is below

```
dependencies {
    compile(project(':react-native-maps')) {
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    } 
     ... Other Deps
    
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.android.gms:play-services-base:10.2.4'
    compile 'com.google.android.gms:play-services-maps:10.2.4'
}
```

My Main application.java
```java
import com.airbnb.android.react.maps.MapsPackage;


@Override
  public List<ReactPackage> createAdditionalReactPackages() {
    // Add the packages you require here.
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            ... Other packages
            new MapsPackage()
    );
  }
```
Versions
```
RN- Maps: 0.17.0
RN: 0.43.0
```

My Mapview component

```javascript
  renderMapView() {
    const region = {
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    };
    return (
      <View style={{ position: 'relative', height: 500}}>
        <MapView
          style={{ left:0, right: 0, top:0, bottom: 0, position: 'absolute' }}
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
        />
      </View>
    );
  }
```

I know this is a duplicate issue, but i've read through all of them and tried what ever they had to offer but kept getting the same error and crash. If someone can help will be usefull. 

i've even tried suggestions mentioned https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f
but still had the same issue

**Comment by charleycesar** [comment]
@nitish24p Try change version version of your SDK in build.gradle to 23 and change compile 
compile 'com.google.android.gms:play-services-base:11.0.4'
compile 'com.google.android.gms:play-services-maps:11.4.2'

**Comment by nitish24p** [comment]
@charleycesar though your solution did work, i dont want to downgrade the build version.. How ever its solved my problem temporarily.

**Comment by charleycesar** [comment]
thanks @nitish24p
