### ISSUE TITLE
Android crashes on startup

### ISSUE THREAD

**Issue by sizovilya** [airbnb/react-native-maps#1777]
Hey guys. 

After plugin installation i have crashes on startup in android version.
**Android monitor shows next error:**
`11-12 20:31:53.627 23964-23993/com.traveler E/AndroidRuntime: FATAL EXCEPTION: Thread-3
                                                              Process: com.traveler, PID: 23964
                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
                                                                  at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52)
                                                                  at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                                  at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:746)
                                                                  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:190)
                                                                  at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69)
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:149)
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:146)
                                                                  at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                                  at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                                  at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1093)
                                                                  at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1064)
                                                                  at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:996)
                                                                  at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:107)
                                                                  at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:832)
                                                                  at java.lang.Thread.run(Thread.java:764)
                                                               Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
                                                                  at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                  at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                  at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52) 
                                                                  at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                                  at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:746) 
                                                                  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:190) 
                                                                  at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:149) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:146) 
                                                                  at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                                  at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1093) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1064) 
                                                                  at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:996) 
                                                                  at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:107) 
                                                                  at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:832) 
                                                                  at java.lang.Thread.run(Thread.java:764) 
                                                               Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
                                                                  at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52) 
                                                                  at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                                  at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:746) 
                                                                  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:190) 
                                                                  at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:149) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:146) 
                                                                  at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                                  at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1093) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1064) 
                                                                  at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:996) 
                                                                  at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:107) 
                                                                  at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:832) 
                                                                  at java.lang.Thread.run(Thread.java:764) 
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.traveler-xGT-czNa-8zpjYC4fUUsbA==/base.apk"],nativeLibraryDirectories=[/data/app/com.traveler-xGT-czNa-8zpjYC4fUUsbA==/lib/arm, /system/fake-libs, /data/app/com.traveler-xGT-czNa-8zpjYC4fUUsbA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                  at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52) 
                                                                  at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                                  at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:746) 
                                                                  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:190) 
                                                                  at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:149) 
                                                                  at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:146) 
                                                                  at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                                  at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1093) 
                                                                  at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1064) 
                                                                  at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:996) 
                                                                  at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:107) 
                                                                  at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:832) 
                                                                  at java.lang.Thread.run(Thread.java:764) `

**My build.gradle:**
```
dependencies {
    compile project(':react-native-maps')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:11.4.2"
    compile "com.google.firebase:firebase-core:11.4.2"
    compile "com.google.firebase:firebase-analytics:11.4.2"
}
```

How to fix it  ?

P.S. I use physical device - nexus 5x with android 8.0.0. 
iOS version works perfectly.

**Comment by shubham81407** [comment]
I have an almost same problem with this package. I have installed this package in my app but it throws and error during runtime in android.

**Comment by mafiusu** [comment]
My App also crashes without an error if I want to render this code on Android

`                <MapView
                    style={[styles.mapView, this.props.mapViewStyle]}
                    cacheEnabled={true}
                    loadingEnabled={true}
                    initialRegion={{
                        latitude: this.props.currentMessage.location.latitude,
                        longitude: this.props.currentMessage.location.longitude,
                        latitudeDelta: 0.0922,
                        longitudeDelta: 0.0421,
                    }}
                    scrollEnabled={false}
                    zoomEnabled={false}>
                        <MapView.Marker 
                            coordinate={{
                                latitude: this.props.currentMessage.location.latitude,
                                longitude: this.props.currentMessage.location.longitude,
                                title: 'Aktuelle Position',
                                description: '...'
                            }}
                        />
                    </MapView>`

**Comment by kevoj** [comment]
guys, u can try with this:
### android/app/build.gradle


```xml

android {...}

// ADD
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('9.8.0')
        }
    }
}

dependencies {...}
```

**Comment by mafiusu** [comment]
@kevoj really nice, it works now on Android. I think it was a problem with the Google Play Service which the code from kevoj has solved.

`
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('9.8.0')
        }
    }
}

dependencies {
    compile project(':react-native-image-resizer')
    compile project(':react-native-maps')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-device-info')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}`

**Comment by sizovilya** [comment]
Hey,
I just add this line 
`compile "com.google.android.gms:play-services-maps:11.4.2"`
to my **android/appp/build.gradle** and android version start working perfectly!

My right dependencies in build.gradle:
```
dependencies {
    compile project(':react-native-maps')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:11.4.2"
    compile "com.google.android.gms:play-services-maps:11.4.2"
    compile "com.google.firebase:firebase-core:11.4.2"
    compile "com.google.firebase:firebase-analytics:11.4.2"
}
```

**Comment by rochapablo** [comment]
I still getting this error

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.doTransform(InstantRunTransform.java:307)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.transform(InstantRunTransform.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor773.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/internal/zzbck
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.android.build.gradle.internal.incremental.IncrementalVisitor$1.getCommonSuperClass(IncrementalVisitor.java:277)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.commons.JSRInlinerAdapter.visitEnd(Unknown Source)
	at org.objectweb.asm.MethodVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at com.android.build.gradle.internal.incremental.IncrementalSupportVisitor.visitMethod(IncrementalSupportVisitor.java:243)
	at org.objectweb.asm.ClassVisitor.visitMethod(Unknown Source)
	at org.objectweb.asm.commons.SerialVersionUIDAdder.visitMethod(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
	at com.android.build.gradle.internal.incremental.IncrementalVisitor.instrumentClass(IncrementalVisitor.java:370)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.transformToClasses2Format(InstantRunTransform.java:406)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.lambda$doTransform$3(InstantRunTransform.java:268)
	at com.android.build.gradle.internal.transforms.InstantRunTransform.lambda$null$4(InstantRunTransform.java:297)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzbck
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
```

*android/app/build.gradle*

```
dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-maps')
    compile project(':react-native-fcm')
    compile project(':react-native-config')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile project(':react-native-photo-view')
    compile "com.android.support:appcompat-v7:27.1.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-maps:11.4.2"
}
```

**Comment by redbluenat** [comment]
I had this error and I updated services for those versions:
```
    compile 'com.google.android.gms:play-services-base:15.0.1'
    compile 'com.google.android.gms:play-services-maps:15.0.1'
    compile 'com.google.android.gms:play-services-places:15.0.1'
    compile 'com.google.android.gms:play-services-location:15.0.1'
```

and it works right now :)

**Comment by vitrum** [comment]
@redbluenat Your post worked well in react native 0.44.3 and react native map 0.15.2.  Thanks.

**Comment by AliZeynalov** [comment]
@kevoj Man you saved my day... Thanks..

**Comment by GleidsonDaniel** [comment]
> I had this error and I updated services for those versions:
> 
> ```
>     compile 'com.google.android.gms:play-services-base:15.0.1'
>     compile 'com.google.android.gms:play-services-maps:15.0.1'
>     compile 'com.google.android.gms:play-services-places:15.0.1'
>     compile 'com.google.android.gms:play-services-location:15.0.1'
> ```
> and it works right now :)

You saved my life! Ty

**Comment by cihanbas** [comment]
> guys, u can try with this:
> 
> ### android/app/build.gradle
> ```
> android {...}
> 
> // ADD
> configurations.all {
>     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>         if (details.getRequested().getGroup() == 'com.google.android.gms') {
>             details.useVersion('9.8.0')
>         }
>     }
> }
> 
> dependencies {...}
> ```

Ohh man Thank you : )
