### ISSUE TITLE
App crashing on sony experia with android 6

### ISSUE THREAD

**Issue by npomfret** [airbnb/react-native-maps#271]
I'm getting this error (only on a sony experia):

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
                                                             at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
                                                             at android.view.SurfaceView.init(SurfaceView.java:207)
                                                             at android.view.SurfaceView.<init>(SurfaceView.java:187)
                                                             at maps.X.x.<init>(Unknown Source)
                                                             at maps.X.v.<init>(Unknown Source)
                                                             at maps.E.u.<init>(Unknown Source)
                                                             at maps.E.u.a(Unknown Source)
                                                             at maps.ag.ad.a(Unknown Source)
                                                             at maps.ag.t.a(Unknown Source)
                                                             at maps.ag.Q.a(Unknown Source)
                                                             at vn.onTransact(:com.google.android.gms.DynamiteModulesB:66)
                                                             at android.os.Binder.transact(Binder.java:387)
                                                             at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
                                                             at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
                                                             at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
                                                             at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
                                                             at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
                                                             at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
                                                             at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                             at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                                                             at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                                                             at com.AirMaps.AirMapView.<init>(AirMapView.java:71)
                                                             at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:70)
                                                             at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:27)
                                                             at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
```

As are a few other people:

https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071

and: https://github.com/lelandrichardson/react-native-maps/issues/165

Does anyone know of a solution?

**Comment by locly** [comment]
I'm working on a fix using the activity context as suggested by others. If you have access to a sony xperia device to test, can you try the fork at https://github.com/locly/react-native-maps/tree/0.4-stable and let me know the outcome and on what device you tested?

1. Change react-native-maps in package.json to be "git://github.com/locly/react-native-maps.git#0.4-stable"
2. Change android/app/src/main/java/com/<yourapp>/MainActivity.java to have "new AirPackage(this)" rather than just new AirPackage().

**Comment by npomfret** [comment]
I made the change and asked someone to try it for me on their sony but they said the app just crashed.  I'll try and get a stack trace from them soon.

**Comment by locly** [comment]
I've pushed another change to use the activity context in the AirMapView.

Have also just got a Z5 Compact here and can confirm it now works without crashing.

Can you update your package.json to this and confirm if it works for you?
"git://github.com/locly/react-native-maps.git#6d393fb6796deb4f8620533cee5c90cb8051d48f"

**Comment by npomfret** [comment]
Should I change `new AirPackage()` to `new AirPackage(this)`?

**Comment by locly** [comment]
Yes, it should be new AirPackage(this)

**Comment by npomfret** [comment]
Ok, looks like that change worked on a Xperia Z5 Compact running Android 6.0

**Comment by locly** [comment]
Great - I'll post to #165 to get others to test and then prep a PR

**Comment by sirwoetang** [comment]
Getting this error on Xiaomi Note 3 Pro.

**Comment by locly** [comment]
@sirwoetang can you post some more info on the error you're getting?

**Comment by sirwoetang** [comment]
@locly, i am quickly stepping through all of the solution variants above and will post the trace if it persists.

**Comment by locly** [comment]
This fix is based on the 0.4-stable branch rather than 0.5, which introduced the change of name - yet to update the 0.5 version.

**Comment by sirwoetang** [comment]
Cool, your fix on this fork works for Xiaomi Note Pro 3 and Xiaomi Mi4c.

**Comment by npomfret** [comment]
Any idea when there will be a release containing the fix?

**Comment by alexHlebnikov** [comment]
Just get this error on Asus ZenPhone 2 (Android 6.0.1).

**Comment by alexHlebnikov** [comment]
Hey guys, after update react-native-maps from master (after this PR: https://github.com/airbnb/react-native-maps/pull/589) the app is no longer crashes with this error!

**Comment by Nurymka** [comment]
The issue still persists on Xiaomi Redmi Note 3.

Android: 5.1
react-native-maps: 0.10.0
react-native: 0.33.1

**Comment by the-simian** [comment]
I am also getting this issue, here is my trace:
<details>
<summary>Stack Trace</summary>

java.lang.NullPointerException Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference 
    ResolutionOverride.java:56 android.util.ResolutionOverride.<init>
    SurfaceView.java:207 android.view.SurfaceView.init
    SurfaceView.java:187 android.view.SurfaceView.<init>
    :com.google.android.gms.DynamiteModulesB:231 com.google.maps.api.android.lib6.gmm6.vector.an.<init>
    :com.google.android.gms.DynamiteModulesB:163 com.google.maps.api.android.lib6.gmm6.vector.ai.<init>
    :com.google.android.gms.DynamiteModulesB:389 com.google.maps.api.android.lib6.gmm6.api.ao.<init>
    :com.google.android.gms.DynamiteModulesB:349 com.google.maps.api.android.lib6.gmm6.api.ao.a
    :com.google.android.gms.DynamiteModulesB:4048 com.google.android.gms.maps.internal.eb.a
    :com.google.android.gms.DynamiteModulesB:403 com.google.maps.api.android.lib6.impl.az.a
    :com.google.android.gms.DynamiteModulesB:308 com.google.maps.api.android.lib6.impl.az.a
    :com.google.android.gms.DynamiteModulesB:79 com.google.maps.api.android.lib6.impl.da.a
    :com.google.android.gms.DynamiteModulesB:66 com.google.android.gms.maps.internal.z.onTransact
    Binder.java:387 android.os.Binder.transact
    Unknown:-1 com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate
    Unknown:-1 com.google.android.gms.maps.MapView$zza.onCreate
    Unknown:-1 com.google.android.gms.dynamic.zza$3.zzb
    Unknown:-1 com.google.android.gms.dynamic.zza$1.zza
    Unknown:-1 com.google.android.gms.maps.MapView$zzb.zzbsp
    Unknown:-1 com.google.android.gms.maps.MapView$zzb.zza
    Unknown:-1 com.google.android.gms.dynamic.zza.zza
    Unknown:-1 com.google.android.gms.dynamic.zza.onCreate
    Unknown:-1 com.google.android.gms.maps.MapView.onCreate
    AirMapView.java:93 com.airbnb.android.react.maps.AirMapView.<init>
    AirMapManager.java:62 com.airbnb.android.react.maps.AirMapManager.createViewInstance
    AirMapManager.java:29 com.airbnb.android.react.maps.AirMapManager.createViewInstance
    ViewManager.java:46 com.facebook.react.uimanager.ViewManager.createView
    NativeViewHierarchyManager.java:218 com.facebook.react.uimanager.NativeViewHierarchyManager.createView
    UIViewOperationQueue.java:149 com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute
    UIViewOperationQueue.java:892 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:865 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedChoreographerFrameCallback.java:32 com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame
    ReactChoreographer.java:131 com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    Choreographer.java:856 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:670 android.view.Choreographer.doCallbacks
    Choreographer.java:603 android.view.Choreographer.doFrame
    Choreographer.java:844 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:743 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:171 android.os.Looper.loop
    ActivityThread.java:5417 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:726 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:616 com.android.internal.os.ZygoteInit.main
</details>

**Comment by iiitmahesh** [comment]
@the-simian Any update ??

**Comment by the-simian** [comment]
@iiitmahesh I still get this issue, but I see it intermittently in our tracker. Unfortunately no updates.
