### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void maps.ad.z.q()' on a null object referenc

### ISSUE THREAD

**Issue by mauron85** [airbnb/react-native-maps#559]
react-native: 0.33-rc.1
platform: Android 6.0.1
plugin version: 0.8.2

When destroying app following exception occurs and app will crash:

```
09-09 12:44:46.020 32731 32731 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void maps.ad.z.q()' on a null object reference
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at maps.ad.R.d(Unknown Source)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at wc.onTransact(:com.google.android.gms.DynamiteModulesB:87)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at android.os.Binder.transact(Binder.java:387)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onDestroy(Unknown Source)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.google.android.gms.maps.MapView$zza.onDestroy(Unknown Source)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.google.android.gms.dynamic.zza.onDestroy(Unknown Source)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.google.android.gms.maps.MapView.onDestroy(Unknown Source)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.airbnb.android.react.maps.AirMapView.doDestroy(AirMapView.java:291)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.airbnb.android.react.maps.AirMapManager.onDropViewInstance(AirMapManager.java:71)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.airbnb.android.react.maps.AirMapManager.onDropViewInstance(AirMapManager.java:27)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:517)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:526)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:417)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:175)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.facebook.react.uimanager.UIViewOperationQueue$3.run(UIViewOperationQueue.java:807)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at android.os.Handler.handleCallback(Handler.java:739)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at android.os.Handler.dispatchMessage(Handler.java:95)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at android.os.Looper.loop(Looper.java:148)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at java.lang.reflect.Method.invoke(Native Method)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-09 12:44:46.020 32731 32731 E AndroidRuntime:       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by felipecsl** [comment]
can you try with React Native `0.32.0`?

**Comment by mauron85** [comment]
will do, just to explain reason to use 0.33-rc.1 It is RN issue https://github.com/facebook/react-native/issues/9791 which is critical for module I'm developing - [react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation/)

**Comment by mauron85** [comment]
Ok. 0.32 is not affected by this. But 0.33 is officially out.

**Comment by BaptisteT** [comment]
Is it related to https://github.com/airbnb/react-native-maps/issues/414 ?

**Comment by mauron85** [comment]
I would say so. Seems like duplicate. Sorry for that.
