### ISSUE TITLE
Android devices crashed

### ISSUE THREAD

**Issue by Clcll** [airbnb/react-native-maps#659]
Hi! I am running my app on android device -
Android version - 5.1.0(lollipop) 
Google Play Services(update yo 9.6.83  234-133155058

Error is
![screenshot_2016-10-07-12-05-00](https://cloud.githubusercontent.com/assets/22677040/19184834/9c06cd0c-8c87-11e6-8f2a-2770cbb75a67.png)

On Google Play Services(with 7.5.0  version app is running but with notification to update Play Services but when click on it app crashed 

Thank you, before hand

**Comment by Clcll** [comment]
![screenshot_2016-10-07-12-32-13](https://cloud.githubusercontent.com/assets/22677040/19185462/68850982-8c8a-11e6-8d37-f0830c6363c2.png)
![screenshot_2016-10-07-12-32-31](https://cloud.githubusercontent.com/assets/22677040/19185466/6a0cc0d8-8c8a-11e6-844f-bed208d204c0.png)
![screenshot_2016-10-07-12-32-25](https://cloud.githubusercontent.com/assets/22677040/19185469/6c1d97ee-8c8a-11e6-8ca9-1b9291b6cb96.png)

**Comment by jeveloper** [comment]
I'd like to report that we have a bunch of people reporting this. 

It might be related to google play services 

see these errors

https://code.google.com/p/gmaps-api-issues/issues/detail?id=10569

@spikebrehm  what do you think?


Here is a stack

```
java.lang.NullPointerException: Attempt to get length of null array
	at maps.G.a.a(Unknown Source)
	at maps.V.N.a(Unknown Source)
	at maps.D.e.a(Unknown Source)
	at maps.D.p.a(Unknown Source)
	at maps.ad.ae.a(Unknown Source)
	at maps.ad.t.a(Unknown Source)
	at maps.ad.R.a(Unknown Source)
	at uo.onTransact(:com.google.android.gms.DynamiteModulesB:66)
	at android.os.Binder.transact(Binder.java:380)
	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zzbru(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:89)
	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:72)
	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:28)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:790)
	at android.view.Choreographer.doCallbacks(Choreographer.java:596)
	at android.view.Choreographer.doFrame(Choreographer.java:556)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5725)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)


```

**Comment by Clcll** [comment]
jeveloper, thank you for your response, how can i sole the issue?

**Comment by jeveloper** [comment]
I'm looking into that as well.

Here are release notes , as the google map app was updated on sept 21st

https://developers.google.com/maps/documentation/android-api/releases

**Comment by jeveloper** [comment]
RN 34.1
Maps 0.10
android 5.1 , 5.0.1, 7.0 and probably others

**Comment by Clcll** [comment]
Thank you, If there's any news let me know)

**Comment by Clcll** [comment]
@jeveloper , I got this after update


`The following build commands failed:
	CompileC /Users/admin/Documents/mobileApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygon.o AirMaps/AIRMapPolygon.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/admin/Documents/mobileApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygonManager.o AirMaps/AIRMapPolygonManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

**Comment by Clcll** [comment]
my package.json 
 


  "dependencies": {
......
    "react-native": "0.34.1",
    "react-native-maps": "^0.10.0",
......
  }

**Comment by jeveloper** [comment]
Looks like you dont have xcode command line tools

no issues here

**Comment by Clcll** [comment]
@jeveloper, 
I still get the same error in Android how it was shown on my screens and in IOS

> The following build commands failed: CompileC /Users/admin/Documents/mobileApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygon.o AirMaps/AIRMapPolygon.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler CompileC /Users/admin/Documents/mobileApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygonManager.o AirMaps/AIRMapPolygonManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

But with this version

"dependencies": {
......
"react-native": "0.34.0",
"react-native-maps": "^0.8.2",
......
}

In IOS everything is ok but in Android also everything  is bad  

Thank you

**Comment by alexHlebnikov** [comment]
Same error on Android, with RN 0.34.1 and rnm 0.8.2.

**Comment by jeveloper** [comment]
this fixed it for me

   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by Clcll** [comment]
@jeveloper Can you post your settings.gradle, build.gradle, app/build.gradle, AndroidManifest.xml and MainApplication.java  the parts which relate to 'react-native-maps', please

Thank you before hand

**Comment by Clcll** [comment]
@alexHlebnikov do you have any ideas ?

**Comment by alexHlebnikov** [comment]
Nope, I can't reproduce it myself, only know form Carash Analytics what my users have it.

**Comment by Clcll** [comment]
@alexHlebnikov  The same

**Comment by Clcll** [comment]
Works for me on 5.1 and 6.0   

"dependencies": {
    .......
    "react": "15.3.1",
    "react-native": "^0.35.0",
    "react-native-maps": "^0.11.0",
    .......
  }
