### ISSUE TITLE
Running on real device crashes 

### ISSUE THREAD

**Issue by shroukkhan** [airbnb/react-native-maps#828]
Hi, 
trying to run it on  real device crashes with the following error:

```
11-25 00:11:32.246 11298-11298/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sagamobile, PID: 11298
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference
                                                       at com.airbnb.android.react.maps.AirMapView$11.run(AirMapView.java:611)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

However, it runs perfectly on emulator.
React native version : 0.35.0
React native map npm : 0.11.0
Device:
   Samsung Galaxy S4 / GT-I9500
   Android 5.0.1

**Comment by DennisSnijder** [comment]
I think this is because you did not compile Google maps with your app.

Try adding this to your build.gradle its dependencies.

`compile 'com.google.android.gms:play-services-maps:+'`

**Comment by DannyelPerez** [comment]
@shroukkhan did you try compiling as @DennisSnijder said? Because I got the same problem... And I want to know if this fixed your issue. Thanks.

**Comment by iiitmahesh** [comment]
:+1:

**Comment by iiitmahesh** [comment]
@DannyelPerez @DennisSnijder  @shroukkhan 
any workaround??

**Comment by minhtc** [comment]
+1
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference
    at com.airbnb.android.react.maps.AirMapView$13.run(AirMapView.java:712)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5438)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by sibelius** [comment]
it looks like map is null here https://github.com/airbnb/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L721

**Comment by iiitmahesh** [comment]
Its works for me `android:hardwareAccelerated="true"`

```
<activity android:name=".MainActivity" android:label="@string/app_name" android:screenOrientation="portrait"  android:hardwareAccelerated="true" android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by DannyelPerez** [comment]
@iiitmahesh really?  I'll try it soon, because I just was ignoring the problem for a time I was doing some things that was more important.

**Comment by philjoseph** [comment]
I've hit the same crash but none of the workarounds here (compile gms:play-services-maps or add android:hardwareAccelerated in the manifest) did help.

Any idea what may causes that crash ?

**Comment by maluramichael** [comment]
I got the same problem

```
"react": "^15.3.1",
"react-native": "0.38.1",
"react-native-maps": "^0.9.0",
```
```
E  java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference
E      at com.airbnb.android.react.maps.AirMapView$11.run(AirMapView.java:569)
E      at android.os.Handler.handleCallback(Handler.java:789)
E      at android.os.Handler.dispatchMessage(Handler.java:98)
E      at android.os.Looper.loop(Looper.java:164)
E      at android.app.ActivityThread.main(ActivityThread.java:6541)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Hoolii** [comment]
I think you should update `react-native-maps`. I'm using `0.16.2` and I don't have the issue anymore.

**Comment by maluramichael** [comment]
@Hoolii do you know if `0.16.2` is still compatible with react-native `0.38.1`?

**Comment by Hoolii** [comment]
@maluramichael Maybe not, I'm using `0.46.4` in my project.
