### ISSUE TITLE
Physical device crash:  No direct method <init>(IJ)V in class

### ISSUE THREAD

**Issue by csavage1994** [airbnb/react-native-maps#861]
I'm trying to get this component to work, but whenever I start the app on my phone the app crashes as soon as the map starts to load. Running `adb logcat` shows the following error when the app crashes:

```
12-05 19:11:22.711 25807 25807 D AndroidRuntime: Shutting down VM
12-05 19:11:22.711 25807 25807 E AndroidRuntime: FATAL EXCEPTION: main
12-05 19:11:22.711 25807 25807 E AndroidRuntime: Process: com.test, PID: 25807
12-05 19:11:22.711 25807 25807 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(IJ)V in class Lcom/facebook/react/uimanager/events/Event; or its super classes (declaration of 'com.facebook.react.uimanager.events.Event' appears in /data/app/com.test-2/base.apk)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.airbnb.android.react.maps.RegionChangeEvent.<init>(RegionChangeEvent.java:16)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapView$8.onCameraChange(AirMapView.java:220)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.google.android.gms.maps.GoogleMap$18.onCameraChange(Unknown Source)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:387)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at yb.a(:com.google.android.gms.DynamiteModulesB:93)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at maps.D.a.a(Unknown Source)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at maps.D.a$1.run(Unknown Source)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7237)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12-05 19:11:22.711 25807 25807 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-05 19:11:22.711  3722  5607 W ActivityManager:   Force finishing activity com.test/.MainActivity
12-05 19:11:22.711  3722  5607 D FocusedStackFrame: Set to : 0
```

here's my dependencies as well:
```
dependencies {
    //compile project(':react-native-maps')
    //compile 'com.airbnb.android:react-native-maps:0.6.0'
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-maps:+'
    compile 'com.google.android.gms:play-services-location:+'
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.airbnb.android:react-native-maps:0.7.1'
    //compile project(':react-native-maps')
}
```

Any help would be appreciated!

**Comment by BigPun86** [comment]
+1

**Comment by BigPun86** [comment]
Which Version of react-native-maps are u using?

I simply updated my build.gradle file with compile project(':react-native-maps')
