### ISSUE TITLE
Updating react-native-maps > 0.8.2 crashes Android

### ISSUE THREAD

**Issue by kevinnguy** [airbnb/react-native-maps#874]
When I update `react-native-maps` to `0.9.0` and higher, my Android app crashes at app startup and it doesn't show an error screen. I've been having a difficult time trying to debug why my app on Android is crashing.

I've tested all versions `0.9.0` and higher and `0.8.2` was the version that didn't crash for me. 

My `package.json`:
```
  "dependencies": {
    "firebase": "3.4.0",
    "lodash": "^4.16.1",
    "react": "15.4.1",
    "react-native": "0.39.0",
    "react-native-maps": "0.8.2",
    "react-native-navigation": "2.0.0-experimental.141",
    "react-redux": "^4.4.5",
    "realm": "^0.14.3",
    "redux": "3.6.0",
    "redux-thunk": "^2.1.0"
  },
```

Any suggestions to debugging Android would be appreciated! Thanks!

**Comment by gilbox** [comment]
try `react-native-maps@0.12.1`?

**Comment by kevinnguy** [comment]
@gilbox I've tried `0.12.1` earlier today and it crashed on me :/

**Comment by gilbox** [comment]
@kevinnguy check your `adb logcat`

**Comment by kevinnguy** [comment]
This is the log I get back from `adb logcat` on `"react-native-maps": "0.12.1"`

```
12-08 14:57:18.336   799   817 I ActivityManager: Displayed com.hero/.MainActivity: +349ms
12-08 14:57:18.511  5809  5809 I art     : Thread[1,tid=5809,Native,Thread*=0xb4d36500,peer=0x748372a0,"main"] recursive attempt to load library "/data/app/com.hero-1/lib/arm/libfb.so"
12-08 14:57:18.512  5809  5809 W unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
12-08 14:57:18.509  1191  1191 W Binder_6: type=1400 audit(0.0:4213): avc: denied { ioctl } for path="socket:[836123]" dev="sockfs" ino=836123 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
12-08 14:57:18.509  1191  1191 W Binder_6: type=1400 audit(0.0:4214): avc: denied { ioctl } for path="socket:[836123]" dev="sockfs" ino=836123 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
12-08 14:57:18.509  1123  1123 W Binder_3: type=1400 audit(0.0:4215): avc: denied { ioctl } for path="socket:[836122]" dev="sockfs" ino=836122 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
12-08 14:57:18.509  1123  1123 W Binder_3: type=1400 audit(0.0:4216): avc: denied { ioctl } for path="socket:[836122]" dev="sockfs" ino=836122 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
12-08 14:57:18.544  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-08 14:57:18.546  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-08 14:57:18.548  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-08 14:57:18.549  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-08 14:57:18.553  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-08 14:57:18.553  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-08 14:57:18.555  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLngBounds>
12-08 14:57:18.555  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLngBounds>
12-08 14:57:18.556  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-08 14:57:18.557  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.MapStyleOptions>
12-08 14:57:18.558  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.MapStyleOptions>
12-08 14:57:18.560  5809  5851 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-08 14:57:18.563  5809  5851 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
12-08 14:57:18.563  5809  5851 E AndroidRuntime: Process: com.hero, PID: 5809
12-08 14:57:18.563  5809  5851 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:204)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:143)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:140)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:862)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	... 3 more
12-08 14:57:18.565   799  1192 W ActivityManager:   Force finishing activity com.hero/.MainActivity
```

Seems like it's complaining here:
```
12-08 14:57:18.563  5809  5851 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
12-08 14:57:18.563  5809  5851 E AndroidRuntime: 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
```

Thanks for the suggestion @gilbox !

**Comment by kevinnguy** [comment]
I guess I'm having the same issue as https://github.com/airbnb/react-native-maps/issues/818

**Comment by gilbox** [comment]
Hmm yeah donno about that particular error. This is the combo I use in genymotion:

        * Google Apps: http://opengapps.org/  **x86 **>** 5.1 **>** mini**
        * Emulator: **Google Nexus 5 - API 22 - 1080x1920**

**Comment by kevinnguy** [comment]
I'm running this on a Nexus 5 device.

**Comment by kevinnguy** [comment]
This fixed my issue https://github.com/airbnb/react-native-maps/issues/831#issuecomment-264889464
