### ISSUE TITLE
App immediately crashes when opening

### ISSUE THREAD

**Issue by bfarrgaynor** [airbnb/react-native-maps#894]
```
    "react": "^15.4.1",
    "react-native": "^0.39.2",
    "react-native-maps": "^0.12.2",
```

Getting crash in android simulator (genymotion latest)

Android 6.0.0 API 23

```
12-14 13:01:20.777 E/AndroidRuntime( 1808): FATAL EXCEPTION: AsyncTask #3
12-14 13:01:20.777 E/AndroidRuntime( 1808): Process: com.cpbox, PID: 1808
12-14 13:01:20.777 E/AndroidRuntime( 1808): java.lang.RuntimeException: An error occurred while executing doInBackground()
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.lang.Thread.run(Thread.java:818)
12-14 13:01:20.777 E/AndroidRuntime( 1808): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:204)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:143)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:140)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:862)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-14 13:01:20.777 E/AndroidRuntime( 1808): 	... 3 more
12-14 13:01:20.778 W/ActivityManager(  766):   Force finishing activity com.cpbox/.MainActivity
12-14 13:01:20.781 D/        (  766): HostConnection::get() New Host Connection established 0xdd50bc10, tid 1460
12-14 13:01:20.804 E/EGL_emulation(  779): tid 779: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
12-14 13:01:20.929 W/art     (  766): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 142ms
12-14 13:01:20.944 D/OpenGLRenderer(  766): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
```

**Comment by bfarrgaynor** [comment]
Confirmed crash also happens on device.

**Comment by bfarrgaynor** [comment]
Confirmed this is unrelated to genymotion.

**Comment by gilbox** [comment]
```
Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
```

**Comment by bfarrgaynor** [comment]
Yeah I installed Google Play Services via Genymotions instructions here https://www.genymotion.com/help/desktop/faq/#google-play-services

The app still crashes on load but there's now nothing in the logs.

Removing the lines for react-native-maps has the app working.

This is after upgrading from an earlier version of maps which was working.

Where might I look to even start debugging?

**Comment by gilbox** [comment]
See if this combo works for you

* Emulator: **Google Nexus 5 - API 22 - 1080x1920**
* Google Apps: http://opengapps.org/  **x86 **>** 5.1 **>** mini**

**Comment by bfarrgaynor** [comment]
Will try. brb

**Comment by bfarrgaynor** [comment]
Similar issue. 

```
12-14 20:00:36.638 V/WindowManager(  701): Adding window Window{3c7e9d4b u0 com.cpbox/com.cpbox.MainActivity} at 2 of 8 (before Window{3288de37 u0 Starting com.cpbox})
12-14 20:00:36.670 D/libEGL  ( 3873): loaded /system/lib/egl/libEGL_emulation.so
12-14 20:00:36.670 D/libEGL  ( 3873): loaded /system/lib/egl/libGLESv1_CM_emulation.so
12-14 20:00:36.677 D/libEGL  ( 3873): loaded /system/lib/egl/libGLESv2_emulation.so
12-14 20:00:36.682 D/        ( 3873): HostConnection::get() New Host Connection established 0xeec396c0, tid 3900
12-14 20:00:36.702 I/OpenGLRenderer( 3873): Initialized EGL, version 1.4
12-14 20:00:36.725 D/OpenGLRenderer( 3873): Enabling debug mode 0
12-14 20:00:36.743 W/EGL_emulation( 3873): eglSurfaceAttrib not implemented
12-14 20:00:36.743 W/OpenGLRenderer( 3873): Failed to set EGL_SWAP_BEHAVIOR on surface 0xeec35be0, error=EGL_SUCCESS
12-14 20:00:36.744 I/Icing   ( 1604): Indexing E66A8A993C3C5EFF0ED1A008DC468D6025B02990 from com.google.android.gms
12-14 20:00:36.753 I/Icing   ( 1604): Indexing done E66A8A993C3C5EFF0ED1A008DC468D6025B02990
12-14 20:00:36.768 I/Icing   ( 1604): Indexing 290F169070E2DEE611547BD67897A0057FD5CE38 from com.google.android.googlequicksearchbox
12-14 20:00:36.791 I/Icing   ( 1604): Indexing done 290F169070E2DEE611547BD67897A0057FD5CE38
12-14 20:00:36.974 I/ActivityManager(  701): Displayed com.cpbox/.MainActivity: +473ms
12-14 20:00:36.982 W/EGL_emulation( 3873): eglSurfaceAttrib not implemented
12-14 20:00:36.982 W/OpenGLRenderer( 3873): Failed to set EGL_SWAP_BEHAVIOR on surface 0xeec35c00, error=EGL_SUCCESS
12-14 20:00:37.520 W/ResourceType( 1036): No package identifier when getting value for resource number 0x00000000
12-14 20:00:37.521 W/PackageManager( 1036): Failure retrieving resources for com.android.launcher3: Resource ID #0x0
12-14 20:00:39.412 I/art     ( 3873): Background sticky concurrent mark sweep GC freed 1956(119KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 1645KB/1833KB, paused 7.286ms total 11.340ms
12-14 20:00:39.470 I/art     ( 3873): Thread[1,tid=3873,WaitingForJniOnLoad,Thread*=0xf3c25800,peer=0x73b34000,"main"] recursive attempt to load library "/data/app/com.cpbox-1/lib/x86/libfb.so"
12-14 20:00:39.471 W/InputMethodManagerService(  701): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@1dfcd7be attribute=null, token = android.os.BinderProxy@3a028e1a
12-14 20:00:39.476 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-14 20:00:39.476 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-14 20:00:39.477 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.477 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.477 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.477 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.477 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLngBounds>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLngBounds>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.LatLng>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.MapStyleOptions>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.model.MapStyleOptions>
12-14 20:00:39.478 I/art     ( 3873): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>
12-14 20:00:39.479 E/AndroidRuntime( 3873): FATAL EXCEPTION: AsyncTask #3
12-14 20:00:39.479 E/AndroidRuntime( 3873): Process: com.cpbox, PID: 3873
12-14 20:00:39.479 E/AndroidRuntime( 3873): java.lang.RuntimeException: An error occured while executing doInBackground()
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.lang.Thread.run(Thread.java:818)
12-14 20:00:39.479 E/AndroidRuntime( 3873): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:204)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:143)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:140)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:862)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-14 20:00:39.479 E/AndroidRuntime( 3873): 	... 3 more
12-14 20:00:39.481 W/ActivityManager(  701):   Force finishing activity 1 com.cpbox/.MainActivity
12-14 20:00:39.492 E/EGL_emulation(  719): tid 719: eglCreateSyncKHR(1209): error 0x3004 (EGL_BAD_ATTRIBUTE)
12-14 20:00:39.651 D/Atlas   (  701): Validating map...
12-14 20:00:39.664 W/DownloadManager( 3741): [1] Stop requested with status HTTP_DATA_ERROR: Unable to resolve host "redirector.gvt1.com": No address associated with hostname
12-14 20:00:39.665 D/DownloadManager( 3741): [1] Finished with status WAITING_TO_RETRY
12-14 20:00:39.671 I/ActivityManager(  701): Killing 3300:com.google.android.apps.maps/u0a72 (adj 15): empty #17
12-14 20:00:39.685 I/OpenGLRenderer(  701): Initialized EGL, version 1.4
12-14 20:00:39.696 D/WifiService(  701): Client connection lost with reason: 4
12-14 20:00:39.710 W/EGL_emulation(  701): eglSurfaceAttrib not implemented
12-14 20:00:39.710 W/OpenGLRenderer(  701): Failed to set EGL_SWAP_BEHAVIOR on surface 0xeec60b20, error=EGL_SUCCESS
12-14 20:00:39.729 W/EGL_emulation( 2669): eglSurfaceAttrib not implemented
12-14 20:00:39.729 W/OpenGLRenderer( 2669): Failed to set EGL_SWAP_BEHAVIOR on surface 0xeec35840, error=EGL_SUCCESS
12-14 20:00:40.184 I/ActivityManager(  701): Killing 3338:com.google.android.gms.feedback/u0a61 (adj 15): empty #17
12-14 20:00:40.369 W/OpenGLRenderer( 2669): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-14 20:00:40.658 W/ResourceType( 1036): No package identifier when getting value for resource number 0x00000000
12-14 20:00:40.658 W/PackageManager( 1036): Failure retrieving resources for com.cpbox: Resource ID #0x0
12-14 20:00:45.675 I/InputReader(  701): Reconfiguring input devices.  changes=0x00000010
12-14 20:00:45.686 W/Finsky  ( 1748): [1] com.google.android.finsky.application.FinskyAppImpl.T(1667): No account configured on this device.
12-14 20:00:45.691 D/BackupManagerService(  701): Received broadcast Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.android.musicfx flg=0x4000010 (has extras) }
12-14 20:00:45.697 I/UpdateIcingCorporaServi( 3441): Updating corpora: APPS=com.android.musicfx, CONTACTS=MAYBE
12-14 20:00:45.703 W/Launcher( 2669): setApplicationContext called twice! old=com.android.launcher3.LauncherApplication@36739041 new=com.android.launcher3.LauncherApplication@36739041
12-14 20:00:45.712 I/UpdateIcingCorporaServi( 3441): UpdateCorporaTask done [took 15 ms] updated apps [took 15 ms] 
12-14 20:00:45.739 I/Icing   ( 1604): Usage reports 0 indexed 0 rejected 0 imm upload false
12-14 20:00:45.746 I/Icing   ( 1604): Usage reports 0 indexed 0 rejected 0 imm upload false
12-14 20:00:45.747 W/IcingInternalCorpora( 1604): getNumBytesRead when not calculated.
12-14 20:00:45.846 W/AudioTrack(  701): AUDIO_OUTPUT_FLAG_FAST denied by client
12-14 20:00:45.858 I/Process ( 3873): Sending signal. PID: 3873 SIG: 9
12-14 20:00:45.879 I/ActivityManager(  701): Process com.cpbox (pid 3873) has died
```

**Comment by gilbox** [comment]
try this
https://github.com/airbnb/react-native-maps/pull/877/files

**Comment by bfarrgaynor** [comment]
Boom. Works.

**Comment by bfarrgaynor** [comment]
Confirmed https://github.com/airbnb/react-native-maps/pull/877/files fixes the crashing issue.
