### ISSUE TITLE
Getting this NullPointerException only when i am running release / signed apk

### ISSUE THREAD

**Issue by BigPun86** [airbnb/react-native-maps#907]
Hey there! 

Like the title says i am receiving following crash report on release / signed apk:

    FATAL EXCEPTION: main
    Process: com.test.app, PID: 22141
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
    at com.airbnb.android.react.maps.AirMapMarker.getIcon(AirMapMarker.java:253)
    at com.airbnb.android.react.maps.AirMapMarker.createMarkerOptions(AirMapMarker.java:281)
    at com.airbnb.android.react.maps.AirMapMarker.getMarkerOptions(AirMapMarker.java:217)
    at com.airbnb.android.react.maps.AirMapMarker.addToMap(AirMapMarker.java:239)
    at com.airbnb.android.react.maps.AirMapView.addFeature(AirMapView.java:391)
    at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:251)
    at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:27)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:379)
    at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:175)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:766)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:813)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:852)
    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5930)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

Any ideas on this?

**Comment by maluramichael** [comment]
Got exactly the same problem. I try to render some pins with an image passed as a prop to the map marker.

**Comment by bfarrgaynor** [comment]
Yes me too.

Map renders ok, but the moment you try to put pins down...

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.airbnb.android.react.maps.AirMapMarker.getIcon(AirMapMarker.java:272)
	at com.airbnb.android.react.maps.AirMapMarker.createMarkerOptions(AirMapMarker.java:301)
	at com.airbnb.android.react.maps.AirMapMarker.getMarkerOptions(AirMapMarker.java:236)
	at com.airbnb.android.react.maps.AirMapMarker.addToMap(AirMapMarker.java:258)
	at com.airbnb.android.react.maps.AirMapView.addFeature(AirMapView.java:398)
	at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:277)
	at com.airbnb.android.react.maps.AirMapManager.addView(AirMapManager.java:29)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:394)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:175)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:628)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7231)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by bfarrgaynor** [comment]
Seems as though this might be related...

**Comment by bfarrgaynor** [comment]
This too #928

**Comment by monumentyusuf** [comment]
+1

**Comment by alexHlebnikov** [comment]
+1

**Comment by engin145** [comment]
+1

**Comment by max-mykhailenko** [comment]
+1

**Comment by wangdaliu** [comment]
+1

**Comment by iiitmahesh** [comment]
+1

**Comment by Geor23** [comment]
+1

**Comment by Geor23** [comment]
@iiitmahesh 
https://github.com/Geor23/react-native-maps/commit/a83c04a4ebb1697e17cf2e77a2f26e9142ea5cc7

**Comment by damathryx** [comment]
+1

**Comment by kevinnguy** [comment]
@Geor23 thanks for the fix! Hopefully you can check it in as a pull request!

**Comment by scotbond** [comment]
+1 with Android 6.0.0 down.
7.0 and up are not prone to this crash for some reason.
