### ISSUE TITLE
Instantly crashes app when running on physical device; "libgnustl_shared.so" is 32-bit instead of 64-bit"

### ISSUE THREAD

**Issue by malithjkmt** [airbnb/react-native-maps#952]
I just downloaded and ran the react-native-maps example app. Built and installed on physical device successfully. First it asks for "Permit drawing over other apps". But then the app crashes instantly when I try to open it. 

`01-12 09:18:47.007 18008 18035 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-12 09:18:47.011   453   453 W auditd  : type=1400 "Binder_1""socket:[4343731]""sockfs"
01-12 09:18:47.011   453   453 W auditd  : type=1400 "Binder_1""socket:[4343731]""sockfs"
01-12 09:18:47.022 18008 18008 D AndroidRuntime: Shutting down VM
01-12 09:18:47.023 18008 18008 E AndroidRuntime: FATAL EXCEPTION: main
01-12 09:18:47.023 18008 18008 E AndroidRuntime: Process: com.airbnb.android.react.maps.example, PID: 18008
01-12 09:18:47.023 18008 18008 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.airbnb.android.react.maps.example/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
01-12 09:18:
libgnustl_shared.so" is 32-bit instead of 64-bit
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at java.lang.Runtime.load(Runtime.java:332)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at java.lang.System.load(System.java:1069)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundFromBundleLoader(XReactInstanceManagerImpl.java:431)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.access$1300(XReactInstanceManagerImpl.java:110)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:416)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5507)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-12 09:18:47.023 18008 18008 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-12 09:18:47.023 18008 18008 D AppTracker: App Event: crash
01-12 09:18:47.025  1313  2158 W ActivityManager:   Force finishing activity com.airbnb.android.react.maps.example/.MainActivity
01-12 09:18:47.049  1313  1358 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6ded226
01-12 09:18:47.049  1313  1358 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4b3e67
01-12 09:18:47.054  1313  1358 W ActivityManager:  Dismiss app error dialog : com.airbnb.android.react.maps.example
01-12 09:18:47.055  1313  1358 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
01-12 09:18:47.057 18008 18008 I Process : Sending signal. PID: 18008 SIG: 9
01-12 09:18:47.066  1313 18037 D DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@2017-01-12-09_18_47_028.txt
01-12 09:18:47.109   732  1739 D APM::AudioPolicyManager: stopOutput() output 2, stream 1, session 28
01-12 09:18:47.110   732  1739 D AudioPolicyManagerCustom: getNewOutputDevice() selected device 0
01-12 09:18:47.110   732  1739 D APM::AudioPolicyManager: setOutputDevice() device 0000 delayMs 96
01-12 09:18:47.119   497   497 E lowmemorykiller: Error writing /proc/18008/oom_score_adj; errno=22
01-12 09:18:47.131  1313  2263 I ActivityManager: Process com.airbnb.android.react.maps.example (pid 18008) has died
01-12 09:18:47.131  1313  4150 D GraphicsStats: Buffer count: 10
01-12 09:18:47.131  1313  2249 I WindowState: WIN DEATH: Window{b9e217c u0 com.airbnb.android.react.maps.example/com.airbnb.android.react.maps.example.MainActivity}
`

**Comment by malithjkmt** [comment]
My device is onePlus 3  Android 6.0.1 (64-bit)
But works on a device Android 5.1.1 (32-bit)
So as I found I need to change the APP_ABI in Application.mk to be compatible with 64-bit 
The Application.mk in react-native/ReactAndroid/src/main/jni/Application.mk is as follow
`APP_BUILD_SCRIPT := Android.mk

APP_ABI := armeabi-v7a x86
APP_PLATFORM := android-9

APP_MK_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

NDK_MODULE_PATH := $(APP_MK_DIR)$(HOST_DIRSEP)$(THIRD_PARTY_NDK_DIR)$(HOST_DIRSEP)$(REACT_COMMON_DIR)$(HOST_DIRSEP)$(APP_MK_DIR)first-party

APP_STL := gnustl_shared

# Make sure every shared lib includes a .note.gnu.build-id header
APP_LDFLAGS := -Wl,--build-id

NDK_TOOLCHAIN_VERSION := 4.8
`
